name: Update EPG
on:
  schedule:
    - cron: "0 */3 * * *"   # каждые 3 часа (UTC)
  workflow_dispatch:        # запуск вручную
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0     # Забираем всю историю для безопасного pull

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python IPTV/scripts/update_epg.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          
          # Забираем последние изменения с GitHub
          git pull origin main --no-rebase
          
          # Добавляем файлы
          git add IPTV/epg.xml.gz IPTV/epg7.xml.gz
          
          # Коммитим (если есть изменения)
          git commit -m "Daily EPG update" || echo "No changes to commit"
          
          # Пушим
          git push origin main
