name: Update EPG

on:
  schedule:
    - cron: "0 */3 * * *"     # каждые 3 часа (UTC)
  workflow_dispatch:          # возможность запустить вручную

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0        # важно для корректного pull

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python IPTV/scripts/update_epg.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"

          # Подтягиваем последние изменения перед коммитом
          git pull origin main --no-rebase || true

          # Добавляем файлы
          git add IPTV/epg.xml.gz IPTV/epg7.xml.gz

          # Коммитим только если есть изменения
          git commit -m "Daily EPG update" || echo "No changes to commit"

          # Пушим изменения
          git push origin main
